### PR TITLE
support multiple sasl_passwd entries

### PR DESCRIPTION
**Pull request by gnowxilef**

### CODE REVIEW

**Comment by gnowxilef** [comment]
poke again?

**Comment by gnowxilef** [comment]
rebased my commit properly. :)

**Comment by gnowxilef** [comment]
can this be reviewed?

**Comment by felix-okta** [comment]
+1

**Comment by thommay** [comment]
Hi @gnowxilef ; sorry for the excessively long delay here. I think the code as it stands is good, but I'd like to see the tests in `test/integration/sasl_auth/serverspec/sasl_auth_spec.rb` updated to confirm that this does the right thing. - ie, populate with one, none and many entries, confirm the file comes out as expected. Sound doable?

**Comment by gnowxilef** [comment]
hi @thommay ; added tests to the cookbook :)

**Comment by gnowxilef** [comment]
can this be merged?

**Comment by felix-okta** [comment]
+1

**Comment by felix-okta** [comment]
@thommay can this PR be merged?

**Comment by felix-okta** [comment]
poke again @thommay or @tas50

**Comment by gnowxilef** [comment]
poke again @thommay or @tas50

**Comment by tas50** [comment]
We've reworked the way the configuration occurs in Postfix and given the user the ability to pass in a lot more arbitrary data. At this PR *may* not be necessary. I'm going to close it out at this point. If you think the functionality is still valid take a look at the current code in master and update the PR to reflect the changes there.

**Comment by gnowxilef** [comment]
i might not be seeing it, but i don't see a place where you can specify more than one saslauth user/password.

**Pull request closed without merging**
