### PR TITLE
added recipient_canonical map entries and etc config

### PR DESCRIPTION
**Pull request by ghost**
Please merge this addition to use recipient_canonical maps.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @cvl-skubriev

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by thommay** [comment]
I'd really like to see some tests here, confirming that if you set the map entries then they get generated properly, and also so that if you have entries set and no map file set, the map file gets set correctly. And so on. Sound doable? I can help you if not.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @vskubriev

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by infertux** [comment]
:+1: I'm also interested in this addition.

@thommay - This new code is pretty much a copy of the one that already handles `sender_canonical` so it might be wise to factorize it with `%w(sender recipient).each do |type| ...` then write a generic test to cover both. I couldn't find any tests which currently covers `sender_canonical_map_entries`. Thoughts?

**Comment by vskubriev** [comment]
I don't have a time to test it or refactor.

**Comment by tas50** [comment]
We've reworked the way the configuration occurs in Postfix and given the user the ability to pass in a lot more arbitrary data. At this PR *may* not be necessary. I'm going to close it out at this point. If you think the functionality is still valid take a look at the current code in master and update the PR to reflect the changes there.

**Pull request closed without merging**
