### PR TITLE
relayhost shouldn't be configured on relay server

### PR DESCRIPTION
**Pull request by mdarii**
### Description

Removed using of normal attribute from recipe postfix::client
node['postfix']['main']['relayhost'] shouldn't be changed if client cookbook is runned on relay host node
### Issues Resolved

Avoid mail sending loop when client cookbook is launched on relay host.

[List any existing issues this PR resolves]

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by mdarii** [comment]
Hi, can somebody have a look?

**Comment by mdarii** [comment]
Hi, any update?

**Comment by tas50** [comment]
We've reworked the way the configuration occurs in Postfix and given the user the ability to pass in a lot more arbitrary data. At this PR *may* not be necessary. I'm going to close it out at this point. If you think the functionality is still valid take a look at the current code in master and update the PR to reflect the changes there.

**Pull request closed without merging**
