### PR TITLE
Added restrictions to main.cf template.

### PR DESCRIPTION
**Pull request by leoditommaso**
Postfix supports restrictions for helo, sender, data, recipient, etc. Those restrictions can be added using simple arrays with the simple changes introduced here.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @leoditommaso

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by leoditommaso** [comment]
Just wanted to know if this could be merged.

Thanks,
Leandro

**Comment by leoditommaso** [comment]
Any news on this?

**Comment by tas50** [comment]
We've reworked the way the configuration occurs in Postfix and given the user the ability to pass in a lot more arbitrary data. At this PR *may* not be necessary. I'm going to close it out at this point. If you think the functionality is still valid take a look at the current code in master and update the PR to reflect the changes there.

**Pull request closed without merging**
