### PR TITLE
Fully manageable master.cf

### PR DESCRIPTION
**Pull request by voroniys**
Change to make full control over master.cf possible
master.cf will be generated from node['postfix']['master']. 
For backwards compatibility attributes/default.rb filled in with content of current master.cf

### CODE REVIEW

**Comment by voroniys** [comment]
With fully customization of master.cf and possibility to create any hash: tables it covers more than 99% of all configuration needs for postfix.

PS. Travis CI build is broken by #112

**Comment by maoueh** [comment]
@voroniys Sorry that my PR caused problems here. I'm back from vacation so still catching up with what happen while I was out. I'm going to investigate this later tonight.

**Comment by voroniys** [comment]
I've closed this pull request and openned the new one - #114 where all issues already solved, including ones caused by #112  - see first commit there.

**Comment by maoueh** [comment]
@voroniys Thanks for fixing this! Seems I hasted at doing the unit tests addition since multiple bugs were in. Sorry :$

**Pull request closed without merging**
