### PR TITLE
Allow pipe delivery methods to be defined from a cookbook/role.

### PR DESCRIPTION
**Pull request by waterkip**
I needed a new delivery method added to master.cf, this wasn't supported by the cookbook. Added support.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @waterkip

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by waterkip** [comment]
Weird, because I signed it..

**Comment by thommay** [comment]
@waterkip Hi, and sorry for the delay. I'd love to get this merged, but please can you make sure your github id is linked to your supermarket account so that your CLA signature shows up? (Hit [https://supermarket.chef.io/profile/link-github](https://supermarket.chef.io/profile/link-github) to make it happen.)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by waterkip** [comment]
I have a signed ICLA, but resigned it.

**Comment by tas50** [comment]
We've reworked the way the configuration occurs in Postfix and given the user the ability to pass in a lot more arbitrary data. At this PR *may* not be necessary. I'm going to close it out at this point. If you think the functionality is still valid take a look at the current code in master and update the PR to reflect the changes there.

**Pull request closed without merging**
